### ISSUE TITLE
Improve CI with official golangci-lint-action

### ISSUE THREAD

**Issue by sczyh30** [opensergo/opensergo-go-sdk#10]
## Issue Description

Type: *feature request*

### Describe what feature you want

Improve CI with official golangci-lint-action.

**Comment by jnan806** [comment]
github reders to [https://github.com/golangci/golangci-lint-action](https://github.com/golangci/golangci-lint-action)

docs refers to [https://golangci-lint.run](https://golangci-lint.run)

**Comment by sczyh30** [comment]
I've split the CI workflow into two parts: lint and test.
See https://github.com/opensergo/opensergo-go-sdk/commit/5e2361943879a2e270d6acbcf58f2dabb6f94da9
