### ISSUE TITLE
Add support for traffic-routing spec v1alpha1

### ISSUE THREAD

**Issue by jnan806** [opensergo/opensergo-go-sdk#24]
## Issue Description

Type: *feature request*

### Describe what feature you want

Now, `traffic-routing spec v1alpha1` has been supported in [opensergo/opensergo-control-plane](https://github.com/opensergo/opensergo-control-plane), so `support for traffic-routing spec v1alpha1` in `OpenSergo GO SDK` also can be put on the schedule.

**Comment by sczyh30** [comment]
@123liuziming Fancy a PR for this? :)
